apiVersion: v1
kind: Secret
metadata:
  name: smartjewel-secret
  labels:
    app: smartjewel-backend
type: Opaque
stringData:
  DB_USER: "postgres.your-project-id"
  DB_PASSWORD: "your-supabase-password"
  JWT_SECRET: "4zV9mK8xL2pQ5wR8tY1uI4oP7sA0dF3gH6jK9lM2nB5vC8xZ1qW4eR7tY0uI3oP"
  SUPABASE_KEY: "your-supabase-key"
