spring:
  application:
    name: smartjewel-backend

  datasource:
    url: ${DB_URL}?prepareThreshold=0
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 86400000

supabase:
  s3:
    endpoint: ${SUPABASE_S3_ENDPOINT:https://zdywhupfukoaiekrywcy.supabase.co/storage/v1/s3}
    region: ${SUPABASE_S3_REGION:us-east-1}
    access-key: ${SUPABASE_S3_ACCESS_KEY:dummy}
    secret-key: ${SUPABASE_S3_SECRET_KEY:dummy}
    bucket-name: ${SUPABASE_STORAGE_BUCKET:product-images}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework: INFO
    com.zaxxer.hikari: DEBUG
    org.hibernate: INFO
    org.postgresql: TRACE
